"""New deadline type 2

Revision ID: 46d09c04bc2b
Revises: 
Create Date: 2026-01-09 21:43:18.903998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from db.types import DDMMYYYY


# revision identifiers, used by Alembic.
revision: str = '46d09c04bc2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'deadline',
               existing_type=sa.VARCHAR(),
               type_=DDMMYYYY(),
               existing_nullable=False,
               postgresql_using="to_date(deadline, 'DD/MM/YYYY')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'deadline',
               existing_type=DDMMYYYY(),
               type_=DDMMYYYY(),
               existing_nullable=False)
    # ### end Alembic commands ###
