"""adding enum defaults

Revision ID: 61ef876e4079
Revises: 935b567b0bd0
Create Date: 2026-01-13 15:39:38.903683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61ef876e4079'
down_revision: Union[str, Sequence[str], None] = '935b567b0bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'DONE', name='taskstatus'),
               server_default='NOT_STARTED',
               existing_nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MODERATE', 'EXTREME', name='taskpriority'),
               server_default='LOW',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MODERATE', 'EXTREME', name='taskpriority'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'DONE', name='taskstatus'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
