"""Adding status

Revision ID: 8ce4e4033b69
Revises: 8d9da428fff9
Create Date: 2026-01-22 00:12:30.728758

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8ce4e4033b69"
down_revision: Union[str, Sequence[str], None] = "8d9da428fff9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "completed_tasks",
        "status",
        existing_type=postgresql.ENUM(
            "NOT_STARTED", "IN_PROGRESS", "DONE", name="taskstatus"
        ),
        server_default="DONE",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "completed_tasks",
        "status",
        existing_type=postgresql.ENUM(
            "NOT_STARTED", "IN_PROGRESS", "DONE", name="taskstatus"
        ),
        server_default=sa.text("'NOT_STARTED'::taskstatus"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
