"""Adding profile_pic column

Revision ID: 8d9da428fff9
Revises: a31afedef59a
Create Date: 2026-01-21 22:29:28.583069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d9da428fff9'
down_revision: Union[str, Sequence[str], None] = 'a31afedef59a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('completed_tasks', 'status',
               existing_type=postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'DONE', name='taskstatus'),
               server_default='NOT_STARTED',
               existing_nullable=False)
    op.add_column('users', sa.Column('profile_pic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    op.alter_column('completed_tasks', 'status',
               existing_type=postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'DONE', name='taskstatus'),
               server_default=sa.text("'DONE'::taskstatus"),
               existing_nullable=False)
    # ### end Alembic commands ###
