"""Trying to change status and priority type

Revision ID: a31afedef59a
Revises: b7013d14fa25
Create Date: 2026-01-14 20:41:17.879756

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a31afedef59a"
down_revision: Union[str, Sequence[str], None] = "b7013d14fa25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column("completed_tasks", "status", server_default=None)

    op.execute("""
        ALTER TABLE completed_tasks
        ALTER COLUMN status
        TYPE taskstatus
        USING status::taskstatus
    """)

    op.alter_column(
        "completed_tasks", "status", server_default=sa.text("'DONE'::taskstatus")
    )

    op.alter_column("completed_tasks", "priority", server_default=None)
    op.execute("""
        ALTER TABLE completed_tasks
        ALTER COLUMN priority
        TYPE taskpriority
        USING priority::taskpriority
    """)
    op.alter_column(
        "completed_tasks", "priority", server_default=sa.text("'LOW'::taskpriority")
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "completed_tasks",
        "priority",
        existing_type=sa.Enum("LOW", "MODERATE", "EXTREME", name="taskpriority"),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        existing_server_default=sa.text("'LOW'::character varying"),
    )
    op.alter_column(
        "completed_tasks",
        "status",
        existing_type=sa.Enum("NOT_STARTED", "IN_PROGRESS", "DONE", name="taskstatus"),
        server_default=sa.text("'DONE'::character varying"),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
