"""Removing autoincreasment for Completed tasks

Revision ID: ba19863aa2cb
Revises: ff01a2584842
Create Date: 2026-01-13 17:47:16.554493

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba19863aa2cb"
down_revision: Union[str, Sequence[str], None] = "ff01a2584842"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "completed_tasks",
        "status",
        existing_type=sa.VARCHAR(),
        server_default="DONE",
        existing_nullable=False,
    )
    op.alter_column(
        "completed_tasks",
        "priority",
        existing_type=sa.VARCHAR(),
        server_default="LOW",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "completed_tasks",
        "priority",
        existing_type=sa.VARCHAR(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "completed_tasks",
        "status",
        existing_type=sa.VARCHAR(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
