"""adding Completed Tasks Table

Revision ID: ff01a2584842
Revises: 61ef876e4079
Create Date: 2026-01-13 16:38:53.877913

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from db.types import DDMMYYYY

# revision identifiers, used by Alembic.
revision: str = "ff01a2584842"
down_revision: Union[str, Sequence[str], None] = "61ef876e4079"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "completed_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("priority", sa.String(), nullable=False),
        sa.Column("deadline", DDMMYYYY(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("completed_tasks")
    # ### end Alembic commands ###
